-- 2-1 사용자 계정 생성 - SYSTEM계정으로 로그인하여 실행
CREATE USER SQLD IDENTIFIED BY 1234; -- 사용자 계정 생성
ALTER USER SQLD ACCOUNT UNLOCK; -- 생성한 사용자 계정의 잠금 해제
GRANT RESOURCE, DBA, CONNECT TO SQLD; -- 생성한 사용자 계정에게 권한부여

-- 2-2 테이블 스페이스 및 임시 테이블 스페이스 생성 - SYSTEM 계정으로 로그인하여 실행
CREATE TABLESPACE SQLD_DATA
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\SQLD_DATA.dbf' SIZE 4G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TEMPORARY TABLESPACE SQLD_TEMP
TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\SQLD_TEMP.dbf' SIZE 1G
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

-- 2-3 디폴트 및 임시 테이블 스페이스 지정 - SYSTEM 계정으로 로그인 하여 실행
ALTER USER SQLD DEFAULT TABLESPACE SQLD_DATA;
ALTER USER SQLD TEMPORARY TABLESPACE SQLD_TEMP;
